bestill/Controllers/ArtistController.cs
using bestill.DAL.Interfaces;
using bestill.Domain.Entity;
using bestill.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using bestill.Domain.ViewModels.Artist;
using System.IO;
using System;

namespace bestill.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IArtistService _artistService;

        public ArtistController(IArtistService artistService)
        {
            _artistService = artistService;
        }

        [HttpGet]
        public IActionResult GetArtists()
        {
            var response = _artistService.GetArtists();
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return View("Error", $"{response.Description}");
        }


        [HttpGet]
        public async Task<IActionResult> GetArtist(int id)
        {
            var response = await _artistService.GetArtist(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }
            return RedirectToAction("Error");
        }

        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _artistService.DeleteArtist(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return RedirectToAction("GetArtists");
            }
            return View("Error", $"{response.Description}");
        }

        [HttpGet]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Save(int id)
        {
            if (id == 0)
            {
                return View();
            }

            var response = await _artistService.GetArtist(id);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View(response.Data);
            }

            return RedirectToAction("Error");
        }

        [HttpPost]

        public async Task<IActionResult> Save(ArtistViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    await _artistService.Create(model);
                }
                else
                {
                    await _artistService.Edit(model.Id, model);
                }
                return RedirectToAction("GetArtists");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Search()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Search(ArtistViewModel model)
        {
            var response = _artistService.Search(model);
            if (response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                return View("SearchResult", response.Data);
            }
            return View("Error", $"{response.Description}");
        }


    }
}

bestill/Views/Artist/Delete.cshtml
@model bestill.Domain.ViewModels.Artist.ArtistViewModel

@{
        ViewBag.Title = "Добавление";
        Layout = "_Layout";
}


@{
    var textTitle = Model?.Id == 0 ? "Изменение данных" : "Добавление данных";
}





<div style="padding: 10px;"></div>
 <div class="col-md-12">
    <div class="card-body">
        <div class="card card-outline-secondary" style="background-color: white">
            <div class="card-header">
                <h3 class="mb-0 text-center ParagraphHome">@textTitle</h3>
            </div>
            <div class="card-body">
                <form asp-action="Save" enctype="multipart/form-data">
                    <input asp-for="Id" hidden />
                    <div asp-validation-summary="All" style="font-size:23px; font-family:Impact, serif" class="text-danger text-center"></div>
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" type="text">
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                    </div>
                    <div class="input-group mb-3">
                      <textarea asp-for="Avatar" class="form-control"></textarea>
                    </div>
                    <button class="btn btn-primary btn-lg float-right" type="submit">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>

bestill/Views/Artist/GetArtist.cshtml
@using bestill.Domain.ViewModels.Artist
@model ArtistViewModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div style="padding: 10px;"></div>
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            <img src=@Model.Avatar 
                 class="img-fluid rounded-start rounded" alt="@Model?.Name">
        </div>
        <div class="col-md-4">
            <div class="card-body">
                <h5 class="card-title text-center">@Model?.Name</h5>
                <p class="card-text"><b>Описание: </b>@Model?.Description</p>
            </div>
        </div>
                           <div class="card-body">
                            <a asp-controller="Album" asp-action="GetAlbums" asp-route-authorId="@Model.Id" class="card-link">Перейти к альбомам</a>
                            @* <a asp-controller="Basket" asp-action="Add" asp-route-id="@id" class="card-link">Добавить</a> *@
                            @if (User.IsInRole("Admin"))
                            {
                                <hr/>
                                <a asp-controller="Car" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Удалить</a>
                                <a asp-controller="Car" asp-action="Save" asp-route-id="@Model.Id" class="btn btn-primary">Изменить</a>
                            }
                        </div>
    </div>
</div>

bestill/Views/Artist/GetArtists.cshtml
@using bestill.Domain.Entity
@model List<Artist>
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<style>
    .card-buttons-group {
        text-align: right;
        padding: 10px;
    }
</style>

<div class="card-buttons-group">
    <button class="btn btn-danger" id='hideCardsId'>Скрыть</button>
    <button class='btn btn-success' id='showCardsId'>Показать</button>
    <a asp-controller="Artist" asp-action="Save" asp-route-id="0" class="btn btn-primary">Добавить</a>
</div>

<div style="padding: 10px;"></div>
@if (Model.Count == 0)
{
    <div class="card col-md-12">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Joan_Baez_Bob_Dylan_crop.jpg/300px-Joan_Baez_Bob_Dylan_crop.jpg"
                     class="img-fluid rounded-start rounded">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title text-center">Список исполнителей пуст :(</h5>
                    <p class="card-text">
                        Список пополнится позже, не расстраивайтесь
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div style="padding: 10px;"></div>
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-pills card-header-pills">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
}
else
{
    <div class="row">
        @foreach (var artist in Model)
        {
            <div class="row row-cols-1 col-md-4 text-center">
                <div class="col" style="padding: 10px;">
                    <div class="card">
                        <img src=@artist.Avatar class="card-img-top"  alt="@artist.Name">
                        <div class="card-body">
                            <h5 class="card-title">@artist.Name</h5>
                            <p class="card-text">@artist.Description</p>
                        </div>

                        <div class="card-body">
                            <a asp-action="GetArtist" asp-route-id="@artist.Id" class="card-link">Перейти</a>
                            

                                <hr/>
                                <a asp-controller="Artist" asp-action="Delete" asp-route-id="@artist.Id" class="btn btn-danger">Удалить</a>
                                <a asp-controller="Artist" asp-action="Save" asp-route-id="@artist.Id" class="btn btn-primary">Изменить</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>   
}

@section pageScripts {
    <script>
        const hideCardElement = $('#hideCardsId');
        const showCardElement = $('#showCardsId');
        const cardElement = $('.card');
        
        const interval = 2000;
        
        hideCardElement.click(function(){
            hideCardElement.hide(interval);
            showCardElement.show(interval);
            cardElement.hide(interval);
        });
        
        showCardElement.click(function () {
            hideCardElement.show(interval);
            showCardElement.hide(interval);
            cardElement.show(interval);
        });
    </script>
}

bestill/Views/Artist/Save.cshtml
@using System;
@using System.Collections;
@using System.Globalization;
@using bestill.Domain.Entity;
@model bestill.Domain.ViewModels.Artist.ArtistViewModel

@{
        ViewBag.Title = "Добавление";
        Layout = "_Layout";
}


@{
    var textTitle = Model?.Id == 0 ? "Изменение данных" : "Добавление данных";
}

@{
    Countries countries = new Countries();
    countries.SetList();
    var countryList = countries.cultureList;

}



<div style="padding: 10px;"></div>
 <div class="col-md-12">
    <div class="card-body">
        <div class="card card-outline-secondary" style="background-color: white">
            <div class="card-header">
                <h3 class="mb-0 text-center ParagraphHome">@textTitle</h3>
            </div>
            <div class="card-body">
                <form asp-action="Save" enctype="multipart/form-data">
                    <input asp-for="Id" hidden />
                    <div asp-validation-summary="All" style="font-size:23px; font-family:Impact, serif" class="text-danger text-center"></div>
                    <div class="form-group">
                        <label asp-for="Name" style="color:black">Имя исполнителя</label>
                        <input asp-for="Name" class="form-control" type="text" id="validationServer01" placeholder="Введите имя исполнителя..." required>
                        <span asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" style="color:black">Описание</label>
                        <textarea asp-for="Description" class="form-control" placeholder="Добавьте описание..."></textarea>
                    </div>
                    <div class="col-md-3">
                     <label for="validationDefault04" style="color:black" class="form-label">Страна</label>
                        <select asp-for="Country" style="align-content" class="form-select" id="validationDefault04" required>
                          <option selected disabled value="">Выберите...</option>
                            @foreach (var country in countryList)
                            {
                                <option>@country</option>
                            }
                            
                        </select>
                      </div>


                    <div class="form-group">
                        <label asp-for="Avatar" style="color:black">Изображение</label>
                      <textarea asp-for="Avatar" class="form-control" placeholder="Вставьте ссылку на изображение..."></textarea>
                    </div>
                                   
                    <li>
                        <input asp-for="Group" type="checkbox">
                        <label asp-for="Group" style="color:black" >Групповой исполнитель</label>
                    </li>
                    
                    <button class="btn btn-primary btn-lg float-right" type="submit">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>

bestill/Views/Artist/Search.cshtml
@using System;
@using System.Collections;
@using System.Globalization;
@using bestill.Domain.Entity;
@model bestill.Domain.ViewModels.Artist.ArtistViewModel

@{
    ViewData["Title"] = "Search";
    Layout = "_Layout";
}

@{
    Countries countries = new Countries();
    countries.SetList();
    var countryList = countries.cultureList;

}


<div style="padding: 10px;"></div>
 <div class="col-md-12">
    <div class="card-body">
        <div class="card card-outline-secondary" style="background-color: white">
            <div class="card-header">
                <h3 class="mb-0 text-center ParagraphHome">Поиск исполнителя</h3>
            </div>
            <div class="card-body">
                <form asp-action="Search" enctype="multipart/form-data">
                    <div asp-validation-summary="All" style="font-size:23px; font-family:Impact, serif" class="text-danger text-center"></div>
                    <div class="form-group">
                        <label asp-for="Name" style="color:black">Имя исполнителя</label>
                        <input asp-for="Name" class="form-control" id="validationServer01" type="text" placeholder="Введите имя исполнителя...">
                    </div>
                                         <div class="col-md-3">
                     <label for="validationDefault04" style="color:black" class="form-label">Страна</label>
                        <select asp-for="Country" style="align-content" class="form-select" id="validationDefault04">
                          <option selected disabled value="">Выберите...</option>
                            @foreach (var country in countryList)
                            {
                                <option>@country</option>
                            }
                            
                        </select>
                      </div>

                <ul class="flex-inner">
                    <li>
                        <input asp-for="Group" type="checkbox">
                        <label asp-for="Group" style="color:black" >Групповой исполнитель</label>
                    </li>
                    </ul>
                    <button class="btn btn-primary btn-lg float-right" type="submit">Искать</button>
                </form>
            </div>
        </div>
    </div>
</div>

bestill/Views/Artist/SearchResult.cshtml
@using bestill.Domain.Entity
@model List<Artist>
@{
    ViewBag.Title = "Search Result";
    Layout = "_Layout";
}

<style>
    .card-buttons-group {
        text-align: right;
        padding: 10px;
    }
</style>

<div class="card-buttons-group">
    <button class="btn btn-danger" id='hideCardsId'>Скрыть</button>
    <button class='btn btn-success' id='showCardsId'>Показать</button>
</div>

<div style="padding: 10px;"></div>
@if (Model is null)
{
    <div class="card col-md-12">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Joan_Baez_Bob_Dylan_crop.jpg/300px-Joan_Baez_Bob_Dylan_crop.jpg"
                     class="img-fluid rounded-start rounded">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title text-center">Список исполнителей пуст :(</h5>
                    <p class="card-text">
                        Список пополнится позже, не расстраивайтесь
                    </p>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="row">
        @foreach (var artist in Model)
        {
            <div class="row row-cols-1 col-md-4 text-center">
                <div class="col" style="padding: 10px;">
                    <div class="card">
                        <img src=@artist.Avatar class="card-img-top" alt="@artist.Name">
                        <div class="card-body">
                            <h5 class="card-title">@artist.Name</h5>
                            <p class="card-text">@artist.Description</p>
                        </div>

                        <div class="card-body">
                            <a asp-action="GetArtist" asp-route-id="@artist.Id" class="card-link">Перейти</a>
                            

                                <hr/>
                                <a asp-controller="Artist" asp-action="Delete" asp-route-id="@artist.Id" class="btn btn-danger">Удалить</a>
                                <a asp-controller="Artist" asp-action="Save" asp-route-id="@artist.Id" class="btn btn-primary">Изменить</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>   
}

@section pageScripts {
    <script>
        const hideCardElement = $('#hideCardsId');
        const showCardElement = $('#showCardsId');
        const cardElement = $('.card');
        
        const interval = 2000;
        
        hideCardElement.click(function(){
            hideCardElement.hide(interval);
            showCardElement.show(interval);
            cardElement.hide(interval);
        });
        
        showCardElement.click(function () {
            hideCardElement.show(interval);
            showCardElement.hide(interval);
            cardElement.show(interval);
        });
    </script>
}